name: Docker Publish
on:
  push:
    branches: [master]
jobs:
  publish:
    if: github.repository == 'NovelCOVID/API'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Denver
      - name: Publish latest to Registry
        uses: docker/build-push-action@v1
        with:
          username: ebwinters
          password: ${{ secrets.Docker_Token }}
          repository: novelcovid/novelcovid-api
          tags: latest
      - name: Publish hashed tag to Registry
        uses: docker/build-push-action@v1
        with:
          username: ebwinters
          password: ${{ secrets.Docker_Token }}
          repository: novelcovid/novelcovid-api
          tag_with_sha: true
  merge-branch:
    if: github.repository == 'NovelCOVID/API'
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'prod'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
