name: Unittest
on:
  push:
    branches: [master]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 */2 * * *"
jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [5]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Denver
      - run: npm run docker-test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASSWORD: ""
          SERVER_PORT: 3000
